### ISSUE TITLE
Can't connect to webpage anymore

### ISSUE THREAD

**Issue by dextraa9791** [linuxserver/docker-bazarr#21] opened 2019-03-25 19:03 UTC
I noticed today that when i browse to http://192.168.2.100:9005/ i can't connect to the bazarr webpage anymore. A couple days ago it was still working fine. I tried restarting my docker bazarr container. I tried making a new config folder and rebuilding the container but i still get the same result. Whenever i start the docker container i don't see any errors in the logs. Does anyone know what this could be?

This is my docker compose config, which hasn't changed.

 bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/bazarr:/config
      - ${SHARE}/movies:/movies
      - ${SHARE}/series:/tv
    ports:
      - 9005:6767
    restart: unless-stopped

**Comment by aptalca** [comment] 2019-03-25 19:08
Post your docker log `docker logs bazarr`

**Comment by dextraa9791** [comment] 2019-03-25 19:14
[bazarr.log](https://github.com/linuxserver/docker-bazarr/files/3005063/bazarr.log)
This is the log from today from my old folder. The new bazarr folder i created hasnt made a .log file yet in the log directory. The portainer log shows the following.

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Bazarr starting...

**Comment by aptalca** [comment] 2019-03-25 19:20
Once it starts, there should be another line like this:
```
2019-03-24 18:11:14,297 - root                             (14c64e8e0b68) :  INFO (main:1937) - BAZARR is started and waiting for request on http://0.0.0.0:6767/bazarr/
```
How long did you wait?

**Comment by dextraa9791** [comment] 2019-03-25 19:25
Hmm, when i go back in the logs i can see that line on the 23th, which is when i restarted my server but after that not anymore. I tried changing the port on my docker host but no lock. I waited like 5 minutes atleast.

**Comment by 19jm81** [comment] 2019-03-26 21:37
Same problem here:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 10-adduser: executing... 

usermod: no changes


-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \ 

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/



Brought to you by linuxserver.io

We gratefully accept donations at:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------


User uid:    911

User gid:    911

-------------------------------------


[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 30-config: executing...

**Comment by Arkhelion** [comment] 2019-03-27 09:58
Issue is reproctible on amd64-9d81ea07-ls26 (current development) and amd64-v0.7.2.1-ls26 (current latest). Issue is not present on amd64-v0.7.2.1-ls25.

**Comment by aptalca** [comment] 2019-03-27 11:53
We can't reproduce it. It works just fine here

**Comment by 19jm81** [comment] 2019-03-27 13:09
I went back to this version: linuxserver/bazarr:arm64v8-a07ddad4-ls25 and now it's working again

**Comment by aptalca** [comment] 2019-03-27 15:03
You need to provide more info as we cannot reproduce it so it is likely discoid to your systems and environment.

Post info on your environment. Hw, OS, docker info, etc

**Comment by Arkhelion** [comment] 2019-03-29 00:12
Docker version :
*******************
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8
 Git commit:   d49b918-synology
 Built:        Wed Feb 27 12:15:55 2019
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8
 Git commit:   d49b918-synology
 Built:        Wed Feb 27 12:15:55 2019
 OS/Arch:      linux/amd64
 Experimental: false

Docker info :
***************
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 38
Server Version: 17.05.0-ce
Storage Driver: btrfs
Logging Driver: db
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: runc
Init Binary: docker-init
containerd version: fd189da3e13a3ef3d6d9eb73c5cd4697b4536cdd (expected: 9048e5e50717ea4497b757314bad98ea3763c145)
runc version: 04b0c8fef1ac449f1a7a51e7c8020c02da1c6735 (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
init version: 7a83305 (expected: 949e6fa)
Security Options:
 apparmor
Kernel Version: 4.4.59+
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.651GiB
Name: *********
ID: *******************************************************
Docker Root Dir: /volume1/@docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support


OS version :
**************
DSM 6.2.1-23824 Update 6

**Comment by jamesking420** [comment] 2019-04-02 15:58
I also have this problem with my QNAP 453 NAS.

**Comment by j0nnymoe** [comment] 2019-04-02 21:51
@jamesking420 tested bazarr on my QNAP and the container is running as expected: 
![image](https://user-images.githubusercontent.com/10374553/55438555-d09fc680-5599-11e9-94ba-ee2db2d26558.png)

**Comment by jamesking420** [comment] 2019-04-03 12:07
Thanks @j0nnymoe  I am beyond confused.  As mentioned LS25 is working but LS26 is not.  Evidently an incompatibility with some systems was introduced at LS26.  Happy to help debug; just need to know exactly what to provide and how.  For theg time being, I will try again one more time with the latest build.

**Comment by j0nnymoe** [comment] 2019-04-03 12:15
I'm not really sure what else you can provide to help debug this. I'm 99% sure it's something specific with your setup because QNAP's all run from the same code base (apart from x86/arm).

In my opinion (I know this might take abit of planning) but I would suggest starting from scratch and redeploy your containers from fresh. There are red flags that haven thrown me off on your setup which I think could be causing conflicts.

For example, when you created the container via container station and you wasn't able to remove the volume locations where as when I tested last night, nothing was prefilled. And also you're using docker volumes instead of mapping the folders to host folders on your QNAP (Like in the guide I provided)

**Comment by jamesking420** [comment] 2019-04-03 12:20
I did spend some time addressing things such as that yesterday - and so I have just redone it exactly as you suggested.  All volumes mapped to pre-existing folders on my drive, and I did not have anything pre-filled in the environment or volume locations.   I just added my PUID, PGID, set network to host, added the volumes, and I was away.  Anyway, it didn't work with the following issue:

https://hastebin.com/efudohanew.sql

Whilst I accept it must be relatively unusual - surely with the log; and knowing what changes went in to LS26, there should be a clue - unfortunately - it's beyond me, & I can understand if you don't want to spend more time on this - I just hope it might help someone in the future in some way.

James

**Comment by j0nnymoe** [comment] 2019-04-03 12:22
ah looking at that log, you're missing the `TZ` variable

```    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')                                                                                                     
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration' ```

**Comment by jamesking420** [comment] 2019-04-03 12:25
I take it that's an environment variable I have to add?

I have noticed that once I have downloaded an image and created a container, if I try and create another image from that container (already on my NAS) then *that* is when I get pre-filled Environment variables, network settings, and Shared folders (that cannot be deleted).  

If I create the container direct from the dockerhub image then I do not have the pre-filled variables.

**Comment by j0nnymoe** [comment] 2019-04-03 12:26
Yea add that as a environment variable.

Ah yes, you always want to be pulling fresh images from docker hub and not from the already downloaded images.

**Comment by jamesking420** [comment] 2019-04-03 12:29
Thank you.

I have noticed that TZ is not in my environment variables for LS25 (which works) - Just FYI really.

I am going to try and figure out what the relevant TZ I need to put in is (I'm in the UK!)  I assume it's like PUID/PGID - I put TZ on the left, and then add <something> on the right hand side?

**Comment by j0nnymoe** [comment] 2019-04-03 12:31
Yea that's pretty much it.

I would say, it's not unusual for a container to boot when not all the information has been provided.

Yea it will be `Europe/London`

**Comment by jamesking420** [comment] 2019-04-03 12:32
> I would say, it's not unusual for a container to boot when not all the information has been provided.

Fair - and logical - I guess I just don't know how to figure out what information it needs!  I'd (naively) understood docker images to beg fairly plug and play.

PS - when I select host mode I get the following warning, although I don't think it really applies in this case:  The port may conflict with the NAS port when selecting Host mode.

**Comment by aptalca** [comment] 2019-04-03 12:35
Check the readme fit the image. It tells you exactly what's needed and provides two examples, one for command line docket create, another for compose

**Comment by j0nnymoe** [comment] 2019-04-03 12:35
All the information to get containers up and running is provided on our readme's at Github and docker hub.

Best to choose NAT (Bridge), then specify the ports in the container information.

**Comment by dextraa9791** [comment] 2019-04-10 18:56
I just tried to install bazarr on a fresh ubuntu 18.04 server but i still have the same problem that the webpage doesn't work.

![afbeelding](https://user-images.githubusercontent.com/47010783/55905803-116b9100-5bd3-11e9-9483-d7dc93ce6652.png)

Here is my docker settings.

**Comment by j0nnymoe** [comment] 2019-04-10 19:02
We've tried this on multiple setups our end and can't replicate the issue ourselves. Any errors in the new logs?

**Comment by dextraa9791** [comment] 2019-04-10 19:05
https://hastebin.com/ocomobatah.cs

This is the log from portainer, i can't see any logs in the config directory

**Comment by dextraa9791** [comment] 2019-04-10 19:07
https://hastebin.com/ejuqofocun.cs Log after deleting bazarr config directory and recreating the docker portainer.

**Comment by j0nnymoe** [comment] 2019-04-10 19:18
How are you installing docker?

**Comment by dextraa9791** [comment] 2019-04-10 19:57
https://docs.docker.com/install/linux/docker-ce/ubuntu/ following this

**Comment by abhishekjainag** [comment] 2019-04-11 21:17
Running into the same issue here, on an Ubuntu Server 16.04 running on a Dell Optiplex, and trying to run Bazarr for the first time. No log files being written, and the docker log stops at "Bazarr starting"

**Comment by j0nnymoe** [comment] 2019-04-11 21:18
@abhishekjainag could you post your docker run command or however you deploy it please.

**Comment by abhishekjainag** [comment] 2019-04-11 22:38
Docker-compose v2:

`bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    network_mode: "host"
    restart: always

    ports:
      - 6767:6767

    volumes:
      - /mnt/media/English Movies:/movies:rw
      - /mnt/media/TV Shows:/tv:rw
      - /srv/app-data/bazarr:/config

    environment:
      - TZ=America/Los_Angeles
      - PUID=1001
      - PGID=1001`

**Comment by j0nnymoe** [comment] 2019-04-11 22:40
Is the `/srv/` mount a remote one? Or a symlink?

**Comment by abhishekjainag** [comment] 2019-04-11 22:42
It's a local path on the computer.../mnt is a mount to my Synology NAS

**Comment by j0nnymoe** [comment] 2019-04-11 22:45
Ok, I'll have to try and spin up a Ubuntu virtual machine and see if we can replicate this. Issue is, we smoke test all our containers before they get pushed to docker hub and it shows it as working: https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/bazarr/v0.7.2.1-ls28/index.html

Just noticed you have ports and host networking defined, You choose either or.

**Comment by abhishekjainag** [comment] 2019-04-11 22:46
Also, just tried this...switching to image: linuxserver/bazarr:v0.7.2.1-ls25 has brought up the web UI, but `docker logs -f bazarr` shows nothing after bazarr starting...a log file was just created in /srv/app-data/bazarr/log (or /config/log), with this line:

`11/04/2019 15:38:32|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|`

**Comment by abhishekjainag** [comment] 2019-04-11 22:48
I tried with neither, as I have been able to get sonarr/radarr working with none of those defined. Now that I have it starting up, I'll be fiddling with this.

**Comment by abhishekjainag** [comment] 2019-04-11 22:59
Okay, so my currently working configuration (at least loading the Web UI) is:

```
  bazarr:
    image: linuxserver/bazarr:v0.7.2.1-ls25
    container_name: bazarr
    restart: always

    volumes:
      - /mnt/media/English Movies:/movies
      - /mnt/media/TV Shows:/tv
      - /srv/app-data/bazarr:/config
    environment:
      - TZ=America/Los_Angeles
      - PUID=1001
      - PGID=1001
```

Now to try removing the tag

**Comment by abhishekjainag** [comment] 2019-04-11 23:29
And weirdly, looks like it's working...one of the other changes I made from when I had initially tried this was switching from TZ="America..." to TZ=America/Los_Angeles.

**Comment by bguscott** [comment] 2019-04-17 04:58
I've run into the same issue as well. 

The latest version doesn't allow me to access the web UI, but rolling back to bazarr:v0.7.2.1-ls25 seems to work just as abhishekjainag reports.

I'm running CentOS 7.6.1810 and my run command is:
```
docker run \
	-d \
	--name=bazarr \
	--restart=always \
	-p 6767:6767 \
	-e PGID=1001 -e PUID=1001 \
	-e TZ="America\Edmonton" \
	-v /etc/localtime:/etc/localtime:ro \
	-v /root/docker/bazarr/config:/config \
	-v /mnt/mediadrive/media/Movies:/Movies \
	-v /mnt/mediadrive/media/TV:/TV \
	-v /mnt/mediadrive/media/Downloads:/Downloads \
linuxserver/bazarr
```

My docker bazarr logs also don't show anything beyond "Bazarr starting...". I've had it running without any issues for a few months but after I recently updated I've been unable to boot the UI. 

Let me know if there's anything I can do to assist troubleshooting.

**Comment by thelamer** [comment] 2019-04-17 05:08
I have confirmed locally clean spinups work fine along with the CI we run https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/bazarr/latest/index.html. 

I also did an "upgrade" from v0.7.2.1-ls25 and it started up , though I have to admit I did not really configure anything . 

Something has to be amiss with the files in config that are not compatible with the current version I less they are generated fresh. 

Don't have anything yet but will try to dig deeper.

**Comment by bguscott** [comment] 2019-04-17 05:24
I deleted the entire '/docker/bazarr' directory (including config) to see if the config was somehow damaged in the "upgrade", but it still fails to boot.

Let me know if there's anything I can try or grab to help test. Thanks!

**Comment by tobbenb** [comment] 2019-04-17 09:42
@bguscott
Your TZ variable is wrong. You got the slash the wrong way. It should be a forward slash /. 
If that doesn't work, check that you installed docker from docker.com and not from a centos repo.

**Comment by bguscott** [comment] 2019-04-17 12:43
@tobbenb thanks for catching that! Unfortunately after fixing it I still can't access the web GUI.

**Comment by tobbenb** [comment] 2019-04-17 13:06
And what about how you installed docker?

**Comment by bguscott** [comment] 2019-04-17 14:38
1. Removing the local time volume mapping made no difference
2. The user has access to the config mount
3. Installed from the docker centos repo (https://download.docker.com/linux/centos/docker-ce.repo)

Any other ideas?

**Comment by tobbenb** [comment] 2019-04-17 15:01
Try removing the config mount and see if it works then.

**Comment by bguscott** [comment] 2019-04-17 15:18
Removing the config mount allows it to boot! This is the command that I ran and I can access the web GUI now:
```
docker run \ 
 -d \
 --name=bazarr \
 --restart=always \
 -p 6767:6767 \
 -e PGID=1001 -e PUID=1001 \
 -e TZ="America/Edmonton" \
 -v /mnt/mediadrive/media/Movies:/Movies \
 -v /mnt/mediadrive/media/TV:/TV \
 -v /mnt/mediadrive/media/Downloads:/Downloads \
 linuxserver/bazarr
```

**Comment by tobbenb** [comment] 2019-04-17 15:24
That means your config mount is the issue. It's either something in the config or permissions.

**Comment by bguscott** [comment] 2019-04-17 15:32
What's weird is I removed the docker image and just re-ran it with the original command and I can access the web GUI again:
```
docker run \
	-d \
	--name=bazarr \
	--restart=always \
	-p 6767:6767 \
	-e PGID=1001 -e PUID=1001 \
	-e TZ="America/Edmonton" \
	-v /etc/localtime:/etc/localtime:ro \
	-v /root/docker/bazarr/config:/config \
	-v /mnt/mediadrive/media/Movies:/Movies \
	-v /mnt/mediadrive/media/TV:/TV \
	-v /mnt/mediadrive/media/Downloads:/Downloads \
linuxserver/bazarr
```
If it was a config issue, it should have been solved when I deleted the old config. If it was a permissions issue, it shouldn't be running right now, no?
When I had it working on `linuxserver/bazarr:v0.7.2.1-ls25` I tried removing it and running `linuxserver/bazarr` again but it didn't boot. 
The only new behaviour was removing the `/config` mount and re-adding it. Any ideas on what the issue could have been?

**Comment by thelamer** [comment] 2019-04-17 21:22
I can replicate this stuff it is all related to the timezone setting, I am gonna PR in setting UTC in env by default, if you run the container with a `-t` flag you will see the following error message: 
```
Traceback (most recent call last):
  File "/app/bazarr/bazarr/main.py", line 24, in <module>
    from update_db import *
  File "/app/bazarr/bazarr/update_db.py", line 7, in <module>
    from scheduler import execute_now
  File "/app/bazarr/bazarr/scheduler.py", line 66, in <module>
    if str(get_localzone()) == "local":
  File "/app/bazarr/bazarr/../libs/tzlocal/unix.py", line 153, in get_localzone
    _cache_tz = _get_localzone()
  File "/app/bazarr/bazarr/../libs/tzlocal/unix.py", line 146, in _get_localzone
    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
```

For everyone having this issue literally copy and paste your timezone from this page: 

https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by thelamer** [comment] 2019-04-17 22:28
With #24 merged and built I am closing this issue. 

If you are still experiencing issues just remove your `-e TZ=` variable from your docker command and see if UTC works for you. If so, you are entering your TZ incorrectly and should reference valid ones from here: 
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Closed by thelamer** 2019-04-17 22:28 UTC
Labels: question

**Comment by dextraa9791** [comment] 2019-04-22 11:50
Tried removing the TZ variable from docker compose, now it does work normal.

Whenever i add my old "Europe/Amsterdam" as timezone, it just breaks again. I have always used "Europe/Amsterdam". Not sure if this is the only timezone with this problem.

**Comment by thelamer** [comment] 2019-04-22 15:00
This issue it closed , the only people that will see comments are people that participated in it in the first place . 
IMPO you should report this kind of stuff upstream to the bazarr devs , it is fine if they want to require a time one, but surely of it is not set the program should not completely crash like this, they need sane error handling and possibly a default UTC value if unset.

**Comment by zachcollard** [comment] 2022-09-13 19:38
September 2022 - went from working for months to not working, this exact issue and same solution.
